/**
 * @file services/Language.js
 * @purpose LANGUAGE: Text/i18n utility. derived from coding_standards.md
 * @standard Singleton, Token-based access.
 */

import { log, l } from '../utils/logger.js';

const TEXTS = {
    // ── CWS COMPLIANCE (consent / disclosure / naturalness) ───────────────────
    CONSENT_TITLE: { en: "How Alchimist handles your text" },
    CONSENT_BODY: { en: "To generate content, Alchimist structures the page content (and any text you select) and sends it to your configured AI service. This is required for the extension to work. Your own API key is used for every request; Alchimist keeps only your settings on this device." },
    CONSENT_PRIVACY: { en: "Privacy policy" },
    CONSENT_ACCEPT: { en: "I understand and agree" },
    DISCLOSURE_BADGE: { en: "Enhanced by Alchimist" },
    UNDO_RESTORE: { en: "Restore original" },
    METRIC_NATURALNESS: { en: "Linguistic Naturalness" },
    METRIC_GOAL_ALIGNMENT: { en: "Goal Alignment" },
    // ── PREMIUM / LICENSE (⚗ Unseal) ──────────────────────────────────────────
    BTN_PREMIUM: { en: "⚗ Unseal" },
    TITLE_PREMIUM_OVERLAY: { en: "Sovereign Tier" },
    MSG_PREMIUM_FEATURES_LIST: { en: "Unlock persona forging, alchemy, intelligence, articles, presets, bundles & multi-key rotation." },
    BTN_BUY_PREMIUM: { en: "Transmute to Sovereign — $25" },
    MSG_PREMIUM_DELIVERY: { en: "After purchase, your license key arrives by email within 24 hours." },
    // [PREMIUM] Per-feature manifest tokens (rendered as a ✔ list by PremiumCover).
    FEATURE_INFINITE_PERSONAS: { en: "Unlimited personas" },
    FEATURE_INFINITE_IMPERATIVES: { en: "Unlimited imperatives" },
    FEATURE_INFINITE_ATTACHMENTS: { en: "Unlimited attachments" },
    FEATURE_INFINITE_METRICS: { en: "Unlimited custom metrics" },
    FEATURE_INFINITE_CHARACTERS: { en: "Unlimited characters" },
    FEATURE_INFINITE_ARCHETYPES: { en: "Unlimited archetypes" },
    FEATURE_INFINITE_PEERS: { en: "Unlimited peers" },
    FEATURE_INFINITE_INTENTS: { en: "Unlimited intents" },
    FEATURE_PERSONA_ALCHEMY: { en: "Persona alchemy" },
    FEATURE_METRIC_ALCHEMY: { en: "Metric alchemy" },
    FEATURE_NEXUS_MODE: { en: "Sequential thread output mode" },
    FEATURE_ALL_PROTOCOLS: { en: "All protocols" },
    FEATURE_ARTICLES: { en: "Articles" },
    FEATURE_PRESETS: { en: "Presets" },
    FEATURE_MULTI_API_KEYS: { en: "Multiple AI API keys" },
    FEATURE_SNAPSHOTS: { en: "Saving/restoring snapshots" },
    LABEL_LICENSE: { en: "License" },
    LABEL_LICENSE_EMAIL: { en: "Email used at purchase" },
    LABEL_LICENSE_KEY: { en: "License key" },
    PLACEHOLDER_LICENSE_KEY: { en: "ALCH-…" },
    BTN_ACTIVATE_LICENSE: { en: "Activate License" },
    BTN_DEACTIVATE_LICENSE: { en: "Deactivate" },
    MSG_LICENSE_FREE_TIER: { en: "Free tier active" },
    MSG_LICENSE_PREMIUM_ACTIVE: { en: "Premium active" },
    MSG_LICENSE_ACTIVATED_AT: { en: "Activated" },
    MSG_LICENSE_SUCCESS: { en: "Premium features unlocked." },
    MSG_LICENSE_ALREADY_ACTIVE: { en: "License already active." },
    ERR_LICENSE_FORMAT: { en: "Invalid key format. Keys start with ALCH-" },
    ERR_LICENSE_MISMATCH: { en: "Key does not match this email. Check both fields." },
    ERR_LICENSE_EMPTY_EMAIL: { en: "Enter the email you used at purchase." },
    ERR_LICENSE_EMPTY_KEY: { en: "Enter your license key." },
    ERR_LICENSE_CRYPTO: { en: "Validation failed. Please try again." },
    ERR_LICENSE_EXPIRED: { en: "Promo key has expired." },
    BTN_REVOKE_SUBSTRATE: { en: "Revoke Substrate" },
    SIGNATURE_DEFAULT: { en: "Transmuted via ΔLCHIMIST 🧪" },
    MSG_TRANSMUTE_STARTED: { en: "Engaging Crucible Void..." },
    MSG_TRANSMUTE_SUCCESS: { en: "Resonance Stabilized." },
    ERR_LLM_FRACTURE: { en: "Crucible communication failed." },
    MSG_PROMPT_FORGED: { en: "Linguistic Siege aggregated." },
    MSG_COMPILATION_ERROR: { en: "Prompt assembly fracture detected." },
    APP_TITLE: { en: "ΔLCHIMIST" },
    APP_SUBTITLE: { en: "Omni-Causal Prime" },
    TITLE_PERSONA: { en: "Persona" },
    TITLE_STRATEGY: { en: "Strategy" },
    TITLE_MODE: { en: "Mode" },
    TITLE_PROTOCOLS: { en: "Protocols" },
    TITLE_DIRECTIVE: { en: "Directive" },
    TITLE_SANCTUARY: { en: "Sanctuary" },
    TITLE_COGNITIVE_AUDITOR: { en: "Cognitive Origin Auditor" },
    DESC_COGNITIVE_AUDITOR: { en: "Analyze linguistic variance to identify none-human generation probability." },
    LABEL_SIGNATURE: { en: "Signature Protocol" },
    DESC_SIGNATURE: { en: "Append persistent tags or sign-offs to generated output." },
    PLACEHOLDER_SIGNATURE: { en: "Enter custom signature..." },
    CAT_MEMORY_MANAGEMENT: { en: "Memory Management" },
    ERR_MEM_GENERIC_OVERFLOW: { en: "Storage overflow." },
    ERR_MEM_PERSONA_CREATE_OVERFLOW: { en: "Persona not created: storage overflow." },
    ERR_MEM_PERSONA_SAVE_OVERFLOW: { en: "Persona not saved: storage overflow." },
    ERR_MEM_PERSONA_KNOWLEDGE_OVERFLOW: { en: "Persona knowledge not saved: storage overflow." },
    ERR_MEM_ATTACHMENT_CREATE_OVERFLOW: { en: "Attachment not created: storage overflow." },
    ERR_MEM_ATTACHMENT_SAVE_OVERFLOW: { en: "Attachment not saved: storage overflow." },
    ERR_MEM_IMPERATIVE_CREATE_OVERFLOW: { en: "Imperative not created: storage overflow." },
    ERR_MEM_IMPERATIVE_SAVE_OVERFLOW: { en: "Imperative not saved: storage overflow." },
    ERR_UNSUPPORTED_FORMAT: { en: "Unsupported file format." },
    SORT_QUANTITY: { en: "quantity" },
    SORT_CREATED: { en: "created time" },
    SORT_USED: { en: "used times" },
    SORT_LAST_USED: { en: "last used time" },
    SORT_ABC: { en: "ABC" },
    WAITING_TRANSMUTING: { en: "Transmuting Text" },
    WAITING_SYNTHESIZING: { en: "Synthesizing Persona" },
    WAITING_FORGING: { en: "Forging Persona Matrix" },
    WAITING_RECALIBRATING: { en: "Recalibrating Metric" },
    WAITING_SUGGESTING: { en: "Applying Suggestion" },
    WAITING_HARVESTING_DATA: { en: "harversting data" },
    WAITING_COMPLETING_ARTICLE: { en: "Completing Article Attributes" },
    STRATEGY_REWRITE: { en: "Rewrite / Post" },
    STRATEGY_COMMENT: { en: "Comment / Thread Reply" },
    STRATEGY_REACTION: { en: "Present / Quote Post" },
    STRATEGY_PROMO: { en: "Promotional Post" },
    STRATEGY_ARTICLE: { en: "Long-form Article" },
    MODE_SINGLE: { en: "Single (1x Variation)" },
    MODE_MATRIX: { en: "Matrix (3x Variations)" },
    MODE_NEXUS: { en: "Nexus (Sequential Thread)" },
    CAT_AUDIT: { en: "Audit" },
    PROT_VOID_AUDITOR: { en: "Void-Source Auditor" },
    DESC_VOID_AUDITOR: { en: "Humanize output." },
    CONFIRM_DELETE_PERSONA: { en: "Are you sure you want to delete this Persona?" },
    READY: { en: "Ready" },
    TRANSMUTING: { en: "Transmuting..." },
    COPY_SUCCESS: { en: "Copied to Clipboard" },
    RECALIBRATE_SUCCESS: { en: "Metrics Recalibrated" },
    MSG_APP_INITIALIZED: { en: "Influence Alchimist Refactored initialized" },
    MSG_PHOENIX_INCINERATING: { en: "Incinerating logic core..." },
    TITLE_CORE: { en: "Influence Core" },
    TITLE_FEATURES: { en: "Intelligence Features" },
    TITLE_PROFILE: { en: "Profile" },
    BTN_HARVEST: { en: "Harvest Profile" },
    BTN_UPDATE: { en: "Update" },
    BTN_CLEAR: { en: "Clear" },
    TITLE_INTELLIGENCE: { en: "Intelligence" },
    TITLE_HOW: { en: "How It Works" },
    TITLE_CONFIG: { en: "Config" },
    TITLE_METRICS: { en: "Resonance Metrics" },
    TITLE_FORGE: { en: "Forge" },
    TITLE_SANCTUARY: { en: "Sanctuary" },
    TITLE_TRANSMUTE: { en: "Transmute" },
    BTN_TRANSMUTE: { en: "Transmute" },
    TITLE_CREATE_PERSONA: { en: "Create Persona" },
    BTN_SAVE_PERSONA: { en: "Save" },
    TITLE_REPOSITORY: { en: "Repository" },
    TITLE_ALCHEMY: { en: "Alchemy" },
    LABEL_NAME: { en: "Name" },
    LABEL_EMOJI: { en: "Emoji" },
    LABEL_TAGS: { en: "Tags (comma separated)" },
    LABEL_DESCRIPTION: { en: "Description" },
    LABEL_PROMPT_RULES: { en: "Prompt / Alchemy Rules" },
    LABEL_LINK_IDENTITY: { en: "Link Identity Anchor" },
    LABEL_PERSONA_LEARNS: { en: "Learning" },
    STATUS_IDLE: { en: "System Ready" },
    ERR_TAB_NOT_FOUND: { en: "No active tab discovered." },
    MSG_SCRAPE_SUCCESS: { en: "Forensic Topology captured via Sovereign Bridge." },
    MSG_BRIDGE_HANDSHAKE: { en: "Initiating Sovereign Bridge Direct Pull..." },
    ERR_SERIALIZATION_FAILURE: { en: "Sovereign bridge serialization poisoned. Attempting storage buffer fallback." },
    MSG_STORAGE_PULL_SUCCESS: { en: "Forensic Topology recovered via Session Storage buffer." },
    MSG_ARCHIVE_GATE_TRIGGERED: { en: "Density Gate triggered: Shielding high-entropy data." },
    TITLE_MAX_SAVED: { en: "Max Saved Outputs" },
    MSG_CRUCIBLE_COLD: { en: "The Crucible is Cold" },
    MSG_CRUCIBLE_SUBTITLE: { en: "Transmute content to fill the archive." },
    BTN_SHOW_ALL: { en: "Show All" },
    BTN_COPY: { en: "Copy to Clipboard" },
    MSG_STABILIZING_DNA: { en: "Stabilizing DNA Synthesis..." },
    LABEL_REFINING: { en: "Refining..." },
    MSG_NO_SIGNAL: { en: "Signal Void Detected" },
    LABEL_VARIATION: { en: "Variation" },
    MSG_CLIPBOARD_SYNCED: { en: "Logs Telepathed to Clipboard" },
    CAT_API_SETTINGS: { en: "API & Model Settings" },
    LABEL_SLOT: { en: "Slot" },
    LABEL_LIVE_BADGE: { en: "LIVE" },
    LABEL_DOWNGRADED: { en: "DOWNGRADED" },
    LABEL_QUOTA_EXPIRED: { en: "Quota Expired" },
    LABEL_API_KEY: { en: "Gemini API Key" },
    PLACEHOLDER_API_KEY: { en: "Paste API Key..." },
    LABEL_PREFERRED_MODEL: { en: "Preferred Model" },
    TITLE_LIMITS: { en: "Limits" },
    LABEL_PERSONA_KNOWLEDGE_THRESHOLD: { en: "Persona Knowledge Threshold" },
    LABEL_MAX_OUTPUTS: { en: "Max Saved Outputs (Sovereign Limit)" },
    PLACEHOLDER_DIRECTIVE: { en: "Directive..." },
    BTN_MANAGE_PERSONAS: { en: "Manage Personas" },
    // [V15] Persona Categories
    TITLE_CATEGORIES:          { en: "Categories" },
    BTN_CREATE_CATEGORY:       { en: "create category" },
    BTN_CREATE:                { en: "Create" },
    TITLE_CREATE_CATEGORY:     { en: "Create Category" },
    TITLE_EDIT_CATEGORY:       { en: "Edit Category" },
    TITLE_DELETE_CATEGORY:     { en: "Delete Category" },
    LABEL_CATEGORY_NAME:       { en: "Category Name" },
    PLACEHOLDER_CATEGORY_NAME: { en: "Enter category name..." },
    BTN_ASSIGN:                { en: "assign" },
    TOOLTIP_ASSIGN_CATEGORY:   { en: "Assign category" },
    TOOLTIP_UNASSIGN_CATEGORY: { en: "Unassign category" },
    CONFIRM_DELETE_CATEGORY:   { en: "Are you sure you want to delete this category?" },
    CAT_ENGAGEMENT: { en: "Engagement" },
    LABEL_KINETICS: { en: "Kinetics" },
    DESC_KINETICS: { en: "Design the final 10% of the message as a 'Hook' to force a reply." },
    LABEL_SOCIAL_ALCHEMY: { en: "Social Alchemy" },
    DESC_SOCIAL_ALCHEMY: { en: "Build multi-node alliances by strategically quoting authors or commenters." },
    LABEL_THEMATIC_TAGGING: { en: "Thematic Tagging" },
    DESC_THEMATIC_TAGGING: { en: "Automatically append context-relevant hashtags to the end of the output." },
    CAT_ENHANCEMENT: { en: "Enhancement" },
    LABEL_EMOJI_ENHANCEMENT: { en: "Emoji" },
    DESC_EMOJI_ENHANCEMENT: { en: "Saturate the output text with appropriate emojis." },
    LABEL_KAOMOJI_ENHANCEMENT: { en: "Kaomoji" },
    DESC_KAOMOJI_ENHANCEMENT: { en: "Append a single, appropriate kaomoji to the end of the text." },
    LABEL_BOLDIFY_ENHANCEMENT: { en: "Boldify" },
    DESC_BOLDIFY_ENHANCEMENT: { en: "Emphasize essential context words/phrases by applying unicode bold." },
    CAT_AUDIT: { en: "Audit" },
    LABEL_VOID_SOURCE: { en: "Void Source Auditor" },
    LABEL_COGNITIVE_AUDIT: { en: "Cognitive Origin Auditor" },
    LABEL_TWITTER_SHORT: { en: "Twitter Short" },
    DESC_TWITTER_SHORT: { en: "Limit output text to no more than 280 symbols." },
    CAT_ADDON: { en: "Addon" },
    LABEL_IMAGE_PROMPT: { en: "Image Prompt" },
    DESC_IMAGE_PROMPT: { en: "Generate AI-ready prompts for visual content matching the response." },
    LABEL_IMAGE_PROMPT_TITLE: { en: "Image Prompt" },
    LABEL_IMPROVE_PROMPT: { en: "Improve Prompt" },
    MSG_IMPROVING: { en: "Refining Visual Logic" },
    WAITING_IMPROVING_PROMPT: { en: "Refining Visual Logic" },
    ERR_IMPROVE_FAILED: { en: "Refinement Fracture." },
    LABEL_DETAILED_SUGGESTIONS: { en: "Detailed Suggestions" },
    DESC_DETAILED_SUGGESTIONS: { en: "Expand suggestion chips into comprehensive long-form strategic refinements." },
    WAITING_MUTATING: { en: "mutating persona" },
    WAITING_CROSSBREEDING: { en: "crossbreeding persona" },
    WAITING_INCREASING_LENGTH: { en: "increasing length" },
    WAITING_DECREASING_LENGTH: { en: "decreasing length" },
    WAITING_INCREASING_VALUE: { en: "Ascending value" },
    WAITING_DECREASING_VALUE: { en: "Descending value" },
    TITLE_IMPERATIVES: { en: "Imperatives" },
    MSG_NO_ATTACHMENTS: { en: "No attachments found. Click \"+ upload file\" below to add knowledge baggage." },
    SUGGESTION_INCREASE_LENGTH: { en: "Increase length of the text, add more details" },
    SUGGESTION_DECREASE_LENGTH: { en: "Decrease length of the text, be more laconic" },
    LOG_INIT_TRANSMUTE: { en: "Transmutation request initiated..." },
    LOG_ERR_TRANSMUTE: { en: "TRANSMUTATION ERROR" },
    LOG_SUC_TRANSMUTE: { en: "Transmutation success!" },
    LOG_INIT_SUGGESTION: { en: "Applying suggestion initiated..." },
    LOG_ERR_SUGGESTION: { en: "APPLYING SUGGESTION FAILED" },
    LOG_SUC_SUGGESTION: { en: "Suggestion applied successfully." },
    LOG_INIT_RECALIBRATE: { en: "Metric recalibration initiated..." },
    LOG_ERR_RECALIBRATE: { en: "METRIC RECALIBRATION ERROR" },
    LOG_SUC_RECALIBRATE: { en: "Metrics recalibrated." },
    LOG_INIT_SYNTHESIS: { en: "Persona synthesis initiated..." },
    LOG_ERR_SYNTHESIS: { en: "SYNTHESIS ABORTED" },
    LOG_SUC_SYNTHESIS: { en: "Persona synthesis complete." },
    LOG_INIT_MUTATE: { en: "Persona mutation initiated..." },
    LOG_ERR_MUTATE: { en: "MUTATION ERROR" },
    LOG_SUC_MUTATE: { en: "Persona mutation complete." },
    LOG_INIT_CROSSBREED: { en: "Persona crossbreeding initiated..." },
    LOG_ERR_CROSSBREED: { en: "CROSSBREEDING ERROR" },
    LOG_SUC_CROSSBREED: { en: "Persona crossbreeding complete." },
    LOG_APP_READY: { en: "Alchimist Core initialized. System ready." },
    LOG_SILENCE: { en: "Silence 💤" },
    BTN_CANCEL: { en: "Cancel" },
    BTN_SAVE: { en: "Save" },
    BTN_UNDO: { en: "Undo" },
    BTN_DELETE: { en: "Delete" },   
    TITLE_PERMISSION_REQUEST: { en: "Webpage Access Permission" },
    MSG_PERMISSION_REQUEST: { en: "Allow Alchimist to read and analyze the content of {hostname}? Access is granted permanently for this site and can be revoked anytime in your browser." },
    BTN_ALLOW: { en: "Allow permanently" },
    LOG_CITADEL_OCCLUDED: { en: "Citadel Occluded" },
    LOG_WARN_WAITING_CANCELLED: { en: "Alchemical process interrupted by user. ✋" },
    ERR_VOID_REJECTION: { en: "The Void rejected the transformation. 🌑" },
    TITLE_INTEGRATIONS: { en: "Integrations" },
    TITLE_CHARS: { en: "Characters" },
    TITLE_ARCHETYPES: { en: "Archetypes" },
    TITLE_SCHEMES: { en: "Schemes" },
    LABEL_CHAR_NAME: { en: "Character Name" },
    LABEL_ARCH_NAME: { en: "Archetype Name" },
    LABEL_ARCH_DESC: { en: "Reasoning/Perspective Description" },
    LABEL_SCHEME_NAME: { en: "Scheme Name" },
    TITLE_NEW_CHAR: {en: "New Character"},
    TITLE_EDIT_CHAR: {en: "Edit Character"},
    TITLE_NEW_ARCHETYPE: {en: "New Archetype"},
    TITLE_NEW_SCHEME: {en: "New Scheme"},
    BTN_CREATE_CHAR: { en: "create char" },
    BTN_CREATE_ARCHETYPE: { en: "create archetype" },
    BTN_CREATE_SCHEME: { en: "create scheme" },
    BTN_CREATE_PEER: { en: "create peer" },
    BTN_CREATE_INTENT: { en: "create intent" },
    FOOTER_ACTION_PRESET: { en: "Preset" },
    FOOTER_ACTION_IMPERATIVE: { en: "Create Imperative" },
    CONFIRM_DELETE_INTEGRATION: { en: "Are you sure you want to delete this integration item?" },
    INTEGRATIONS_DROPDOWN_PLACEHOLDER: { en: "Select integrations" },
    INTEGRATIONS_CHARS_LABEL: { en: "Characters" },
    INTEGRATIONS_ARCHETYPES_LABEL: { en: "Archetypes" },
    INTEGRATIONS_SCHEMES_LABEL: { en: "Schemes" },
    INTEGRATIONS_NO_ACTIVE_INTEGRATIONS: { en: "<i>no active integrations</i>" },
    INTEGRATIONS_EMPTY_GROUP: { en: "None available" },
    TITLE_EDIT_PRESET:        { en: "Edit Preset" },
    TITLE_CREATE_PRESET:      { en: "Create Preset" },
    FOOTER_ACTION_UPLOAD:      { en: "Upload file" },
    PLACEHOLDER_PRESET_NAME:  { en: "Enter preset name..." },
    MSG_NO_PRESETS:           { en: "No presets available." },
    CONFIRM_DELETE_PRESET:    { en: "Are you sure you want to delete this preset?" },
    TOOLTIP_PRESET_RESET:     { en: "Reset Forge to defaults" },
    TITLE_INTELLIGENCE_PEER:   { en: "Peer" },
    TITLE_INTELLIGENCE_INTENT: { en: "Intent" },
    
    TITLE_ARTICLES:                       { en: "Articles" },
    TITLE_LIBRARY:                        { en: "Library" },
    STAGE_ARTICLE_PREPARATION:            { en: 'Stage: article "{title}" preparation' },
    STAGE_ARTICLE_GENERATION:             { en: 'Stage: article "{title}" generation' },
    MSG_MATERIALS_PREPARATION_IN_PROCESS: { en: "materials preparation in process" },
    MSG_NO_ARTICLES:                      { en: "No articles available." },
    MSG_LIBRARY_EMPTY:                    { en: "The Library is empty. Generate an article to fill it." },
    LABEL_MATERIALS_COUNT:                { en: "materials count: {n}" },
    TITLE_CREATE_ARTICLE:                 { en: "Create Article" },
    TITLE_EDIT_ARTICLE:                   { en: "Edit Article" },
    PLACEHOLDER_ARTICLE_TITLE:            { en: "Enter article title..." },
    LABEL_ARTICLE_TITLE:                  { en: "Title" },
    LABEL_ARTICLE_THEME:                  { en: "Theme / Angle" },
    LABEL_ARTICLE_AUDIENCE:               { en: "Target Audience" },
    LABEL_ARTICLE_TONE:                   { en: "Tone & Style" },
    LABEL_ARTICLE_NARRATIVE_MODEL:        { en: "Narrative Model" },
    LABEL_ARTICLE_ANCHOR:                 { en: "Narrative Anchor (Poster Child)" },
    LABEL_ARTICLE_COMPLICATION:           { en: "Central Complication" },
    LABEL_ARTICLE_FORMAT:                 { en: "Format" },
    LABEL_ARTICLE_WORD_COUNT:             { en: "Target Word Count" },
    LABEL_ARTICLE_REQUIRED_CONTENT:       { en: "Required Content / Sources" },
    LABEL_ARTICLE_VERIFICATION:           { en: "Verification & Safety Standard" },
    LABEL_ARTICLE_ATTRIBUTES:             { en: "Attributes" },
    LABEL_IMAGE_PROMPT_TITLE_N:           { en: "Image Prompt {n}" },
    LABEL_MAX_SAVED_ARTICLES:             { en: "Max Saved Articles" },
    CONFIRM_DELETE_ARTICLE:               { en: "Are you sure you want to delete this article?" },
    BTN_AUTOFILL_ARTICLE:                 { en: "Auto-fill remaining fields with AI" },
    MSG_AUTOFILL_NO_TITLE:                { en: "Enter a title of at least 10 characters before auto-filling." },
    MSG_AUTOFILL_DONE:                    { en: "Empty attributes saturated by the Crucible." },
    FOOTER_ACTION_ARTICLE:                { en: "Create Article" },
    ERR_ARTICLE_NO_ACTIVE:                { en: "No active article. Select or create an article to generate a long-form piece." },
    ERR_ARTICLE_NO_MATERIALS:             { en: "Active article has no materials. Run a preparation transmutation first." },
    WAITING_ARTICLE_GENERATING:           { en: "Forging Long-form Article" },
    LOG_INIT_ARTICLE_GEN:                 { en: "Article generation initiated..." },
    LOG_SUC_ARTICLE_GEN:                  { en: "Article forged successfully." },
    LOG_ERR_ARTICLE_GEN:                  { en: "ARTICLE GENERATION ERROR" },
    SCHEMA_INJECTION_ARTICLE_MATERIALS:   { en: '\n[MANDATORY FIELD]: You MUST include "article_materials_reasoning" (string) and "update_article_materials" (array) in your root JSON object following the ARTICLE_MATERIALS_UPDATE_PROTOCOL.' }
    ,
    LABEL_MATERIALS_ADVICE:               { en: "{advice}" },
    LABEL_ARTIFACTS_PERSONA_ADDED:        { en: "Added Persona Knowledge" },
    LABEL_ARTIFACTS_PERSONA_SYNTHESIZED:  { en: "Synthesized Persona Knowledge" },
    LABEL_ARTIFACTS_ARTICLE_ADDED:        { en: "Added Article Materials" },
    LABEL_ARTIFACTS_ARTICLE_SYNTHESIZED:  { en: "Synthesized Article Materials" },

    // ===== Treasury (substrate translocation) =====
    CAT_TREASURY:                          { en: "Treasury" },
    BTN_SNAPSHOT_SAVE:                     { en: "Save Snapshot" },
    BTN_SNAPSHOT_UPLOAD:                   { en: "Upload Snapshot" },
    LABEL_FULL_REPLACE:                    { en: "Full replace" },
    BTN_OVERWRITE:                         { en: "Overwrite" },
    BTN_INTEGRATE:                         { en: "Integrate" },
    CONFIRM_TREASURY_OVERWRITE_TITLE:      { en: "Overwrite Treasury" },
    CONFIRM_TREASURY_OVERWRITE_MSG:        { en: "All current personas, tags, imperatives, attachments, metrics, presets, peers, intents, articles, characters, archetypes, schemes and profile data will be erased and replaced by the snapshot. Continue?" },
    LOG_SUC_SNAPSHOT_SAVED:                { en: "Snapshot successfully saved!" },
    LOG_SUC_SNAPSHOT_OVERWRITTEN:          { en: "Snapshot restored — all data overwritten!" },
    LOG_SUC_SNAPSHOT_INTEGRATED:           { en: "Snapshot successfully integrated!" },
    LOG_WARN_SNAPSHOT_PARTIAL:             { en: "Snapshot partially integrated!" },
    LOG_ERR_SNAPSHOT_CORRUPTED:            { en: "FAIL: snapshot is corrupted" },
    LABEL_ARTIFACTS_TREASURY_ADDED:        { en: "Integrated Records" },
    LABEL_ARTIFACTS_TREASURY_FAILED:       { en: "Failed Records" },
    MSG_TREASURY_STAGED_FILE:              { en: "File staged: {filename}" },
    LABEL_TREASURY_DOMAIN_RESTORED:        { en: "{domain} restored" },
    LABEL_TREASURY_DOMAIN_FAILED:          { en: "{domain} failed: {err}" },
    LABEL_TREASURY_RECORD_ADDED:           { en: "{domain}: \"{name}\" added" },
    WAITING_INTEGRATING_TREASURY:          { en: "Restoring Treasury" },

    // ===== [V14] Forge Metrics =====
    TITLE_FORGE_METRICS:                   { en: "Metrics" },
    BTN_MANAGE_METRICS:                    { en: "Manage Metrics" },
    BTN_CREATE_METRIC:                     { en: "create metric" },
    TITLE_CREATE_METRIC:                   { en: "CREATE METRIC" },
    TITLE_EDIT_METRIC:                     { en: "EDIT METRIC" },
    TITLE_DELETE_METRIC:                   { en: "Delete Metric" },
    MSG_CONFIRM_DELETE_METRIC:             { en: "Are you sure you want to delete this metric?" },
    MSG_NO_METRICS:                        { en: "No metrics defined." },
    LABEL_METRIC_NAME:                     { en: "Name" },
    LABEL_METRIC_DESC:                     { en: "Description" },
    PLACEHOLDER_METRIC_NAME:               { en: "Enter metric name..." },
    PLACEHOLDER_METRIC_DESC:               { en: "Describe what this metric measures..." },
    TITLE_INVENTORY:                       { en: "Inventory" },
    FOOTER_ACTION_METRIC:                  { en: "Create Metric" },
    ERR_MEM_METRIC_CREATE_OVERFLOW:        { en: "Metric not created: storage overflow." },
    ERR_MEM_METRIC_SAVE_OVERFLOW:          { en: "Metric not saved: storage overflow." },
    ERR_METRIC_NAME_RESERVED:              { en: "Name conflicts with an AI-defined metric. Choose a different name." },
    ERR_METRIC_NAME_EMPTY:                 { en: "Metric name cannot be empty." },
    MSG_NO_FAVORITE_PRESETS:               { en: "No favorite presets yet"},
    BTN_METRIC_INTEGRATE:                  { en: "Integrate Metric" },
    BTN_METRIC_RESYNTH:                    { en: "Re-Synth" },
    BTN_METRIC_REEVO:                      { en: "Re-Evo" },
    BTN_METRIC_REMERGE:                    { en: "Re-Merge" },

    // ===== [V14] Metric Alchemy =====
    MSG_METRIC_SYNTH_INTRO:                { en: "Analyzes {context} to forge a unique metric blueprint from the noise." },
    LABEL_BASE_INDICATOR:                  { en: "BASE INDICATOR" },
    LABEL_METRIC_1:                        { en: "METRIC-1" },
    LABEL_METRIC_2:                        { en: "METRIC-2" },
    BTN_METRIC_SELECT_DIFFERENT:           { en: "SELECT DIFFERENT METRICS" },
    WAITING_SYNTHESIZING_METRIC:           { en: "Synthesizing Metric" },
    WAITING_MUTATING_METRIC:               { en: "Mutating Metric" },
    WAITING_CROSSBREEDING_METRIC:          { en: "Crossbreeding Metrics" },
    LOG_INIT_METRIC_SYNTH:                 { en: "Metric synthesis initiated..." },
    LOG_SUC_METRIC_SYNTH:                  { en: "Metric synthesis complete." },
    LOG_ERR_METRIC_SYNTH:                  { en: "METRIC SYNTHESIS ABORTED" },
    LOG_INIT_METRIC_MUTATE:                { en: "Metric mutation initiated..." },
    LOG_SUC_METRIC_MUTATE:                 { en: "Metric mutation complete." },
    LOG_ERR_METRIC_MUTATE:                 { en: "METRIC MUTATION ERROR" },
    LOG_INIT_METRIC_CROSS:                 { en: "Metric crossbreeding initiated..." },
    LOG_SUC_METRIC_CROSS:                  { en: "Metric crossbreeding complete." },
    LOG_ERR_METRIC_CROSS:                  { en: "METRIC CROSSBREEDING ERROR" },
    LOG_SUC_METRIC_INTEGRATED:             { en: "Custom metric integrated." },
    TITLE_SYNTHESIS_METRICS:               { en: "Synth Metrics" },
    TITLE_SYNTHESIS:                       { en: "Synth Personas" },
    TITLE_MUTATION_METRICS:                { en: "Mutate Metrics" },
    TITLE_MUTATION:                        { en: "Mutate Personas" },
    TITLE_CROSSBREED_METRICS:              { en: "Crossbreed Metrics" },
    TITLE_CROSSBREED:                      { en: "Crossbreed Personas" },
    BTN_EXECUTE_SYNTHESIS_METRIC:          { en: "Synthesize Metric" },
    BTN_EXECUTE_SYNTHESIS:                 { en: "Synthesize Persona" },
    BTN_EXECUTE_MUTATION_METRIC:           { en: "Execute Mutation" },
    BTN_EXECUTE_MUTATION:                  { en: "Execute Mutation" },
    BTN_INITIATE_HYBRIDIZATION_METRIC:     { en: "Initiate Hybridization" },
    BTN_INITIATE_HYBRIDIZATION:            { en: "Initiate Hybridization" },
    LABEL_INTEGRATION:                     { en: "Integration" },
    SORT_TOGGLE_DESC:                      { en: "Toggle sort direction" },
    GATEWAY_STATUS_EDITOR_ACTIVE:          { en: "Editor Active" },

    TUTORIAL_SYS_INTEL:                    { en: "System Intelligence (01 / 02)" },
    TUTORIAL_CTX_RET:                      { en: "Context Retainer (02 / 02)" },
    TUTORIAL_API_TITLE:                    { en: "API Configuration (02 / 02)" },
    TUTORIAL_H1:                           { en: "01. Autonomous Thread Isolation" },
    TUTORIAL_D1:                           { en: "Alchimist automatically analyzes the entire page structure, filtering out peripheral noise to isolate and focus on the primary thread (such as the main post)." },
    TUTORIAL_H2:                           { en: "02. Selective Target Alignment" },
    TUTORIAL_D2:                           { en: "When you select text, Alchimist instantly narrows its focus to your selection, while maintaining the broader context of the post and surrounding comments for context-aware responses." },
    TUTORIAL_BTN_NEXT:                     { en: "next: get api key" },
    TUTORIAL_BTN_SKIP:                     { en: "skip" },
    TUTORIAL_API_LINK:                     { en: "https://aistudio.google.com/" },
    TUTORIAL_API_STEP1:                    { en: "Get API Key" },
    TUTORIAL_API_STEP2:                    { en: "Create New Key" },
    TUTORIAL_API_NOTE:                     { en: "(with some free usage)" },
    TUTORIAL_BTN_INIT:                     { en: "Initialize Engine" },
    ART_TUT_TITLE:                         { en: "How article creation works" },
    ART_TUT_STAGE1_EYEBROW:                { en: "Stage 01 / 02 · Preparation" },
    ART_TUT_BG_TAG:                        { en: "background" },
    ART_TUT_H1:                            { en: "01. Materials gather as you work" },
    ART_TUT_D1:                            { en: "While an article is active, every Transmute you run quietly does a second job: it mines the current page for evidence and folds it into the article's material base. Nothing extra to press, it accrues in the background, and the materials count climbs with each pass." },
    ART_TUT_STAGE2_EYEBROW:                { en: "Stage 02 / 02 · Generation" },
    ART_TUT_H2:                            { en: "02. Switch Strategy to Long-form Article" },
    ART_TUT_D2:                            { en: "Pick Long-form Article as your Strategy and the next Transmute stops gathering and starts writing, forging the full piece from materials you collected plus imperatives & attachments, if you want to use them, structured by the chosen narrative model." },
    ART_TUT_LBL_THREAD:                    { en: "Thread" },
    ART_TUT_LBL_ARTICLE:                   { en: "Article" },
    ART_TUT_LBL_STRATEGY:                  { en: "Strategy" },
    ART_TUT_LBL_MATERIALS:                 { en: "materials" },
    ART_TUT_LBL_TRANSMUTE:                 { en: "transmute" },
    ART_TUT_LBL_FROM_MATERIALS:            { en: "from materials" },
    ART_TUT_BTN_UNDERSTOOD:                { en: "Understood" },
    ART_TUT_HELP_TOOLTIP:                  { en: "How creating an article works" },
    CODEX_TITLE:                           { en: "Codex of Transmutation" },
    CODEX_SUBTITLE:                        { en: "Master the Omni-Causal Resonance Engine interface protocols." },
    CODEX_SEARCH_PLACEHOLDER:              { en: "Filter codex aspects or strategies..." },
    TITLE_BUNDLES:                         { en: "Bundles" },
    TITLE_BUNDLES_AREA:                    { en: "Substrate Bundles" },
    BUNDLE_DEFAULT_NAME:                   { en: "Default Substrate" },
    LABEL_BUNDLE_AESTHETIC:                { en: "Aesthetic" },
    LABEL_BUNDLE_VULNERABILITY:            { en: "Core Vulnerability" },
    BTN_APPLY_BUNDLE:                      { en: "Apply Bundle" },
    BTN_REVOKE_BUNDLE:                     { en: "Revoke Bundle" },
    TITLE_REVOKE_BUNDLE:                   { en: "Revoke Bundle" },
    CONFIRM_REVOKE_BUNDLE:                 { en: "Are you sure? This will remove all of this bundle's personas (and their related presets), characters, archetypes, and intents. Resources shared with other applied bundles are removed too; this cannot be undone." },
    MSG_NO_PERSONAS:                       { en: "No personas available." },
    MSG_NO_PERSONA_SELECTED:               { en: "<no persona selected>" },
    ERR_NO_PERSONA:                        { en: "No persona selected — select a persona first." },
    BUNDLE_LABEL_PERSONAS:                 { en: "Personas" },
    BUNDLE_LABEL_CHARS:                    { en: "Characters" },
    BUNDLE_LABEL_ARCHETYPES:               { en: "Archetypes" },
    BUNDLE_LABEL_INTENTS:                  { en: "Intents" }
};

export const Language = {
    current: 'en',

    /**
     * [LXXX] The Great Translator
     * Returns the string for the given token. Fallback to token ID if missing.
     */
    text(token) {
        const entry = TEXTS[token];
        if (!entry) {
            l('LANGUAGE_MISSING_TOKEN', { token });
            return token;
        }
        return entry[this.current] || entry['en'] || token;
    },

    setLanguage(lang) {
        this.current = lang;
        l('LANGUAGE_SET', { lang });
    }
};

// Global attachment for specification_protocol compliance
window.text = (token) => Language.text(token);